### ISSUE TITLE
How I can install this tool on ubuntu 16.04 ?

### ISSUE THREAD

**Issue by stavskiys** [kekekeks/skypetab-ng#79]

**Comment by kekekeks** [comment]
Old deb package is still compatible - https://launchpad.net/~keks9n/+archive/ubuntu/skypetab/+build/6111415/+files/skypetab-ng_0.5.3-ubuntu_all.deb

**Comment by stavskiys** [comment]
More than 3 years I use yours app. Thank you a lot. Great job!
